import { expect, test } from '@playwright/test'
import { promises as fs } from 'node:fs'
import { join } from 'node:path'

const decksDir = join(process.cwd(), 'content', 'investments')
const runId = `${Date.now()}`
const publishedSlug = `e2e-published-${runId}`
const draftSlug = `e2e-draft-${runId}`
const publishedTitle = `E2E Published Pitch Deck ${runId}`
const draftTitle = `E2E Draft Pitch Deck ${runId}`
const publishedDeckPath = join(decksDir, `${publishedSlug}.yml`)
const draftDeckPath = join(decksDir, `${draftSlug}.yml`)

function buildDeckYml(title: string, published: boolean): string {
  return `title: ${title}
projectName: E2E Verification Complex
audienceType: investor
published: ${published}
cover:
  enabled: true
  body: Generated by Playwright to validate deck creation flow.
executiveSummary:
  enabled: true
  body: This confirms newly created deck content renders in the public deck view.
`
}

test.beforeAll(async () => {
  await fs.writeFile(publishedDeckPath, buildDeckYml(publishedTitle, true), 'utf8')
  await fs.writeFile(draftDeckPath, buildDeckYml(draftTitle, false), 'utf8')
})

test.afterAll(async () => {
  await Promise.all([
    fs.rm(publishedDeckPath, { force: true }),
    fs.rm(draftDeckPath, { force: true })
  ])
})

test('newly created published investments are listed and render correctly', async ({ page }) => {
  await page.goto('/investments')

  await expect(page.getByRole('heading', { name: 'Active Offering Investments' })).toBeVisible()
  await expect(page.getByText(publishedTitle)).toBeVisible()
  await expect(page.getByText(draftTitle)).toHaveCount(0)

  await page.getByRole('link', { name: new RegExp(publishedTitle) }).click()
  await expect(page).toHaveURL(new RegExp(`/investments/${publishedSlug}$`))
  await expect(page.getByRole('heading', { name: publishedTitle })).toBeVisible()
  await expect(page.getByText('Generated by Playwright to validate deck creation flow.')).toBeVisible()
})

test('newly created unpublished investments stay private', async ({ page }) => {
  const response = await page.goto(`/investments/${draftSlug}`)
  expect(response?.status()).toBe(404)
})
